const ITEMS = [{"seq": 1, "location": "Chicken Cooler", "name": "Chicken", "packSize": "8 bags", "pack": 8}, 
    {"seq": 2, "location": "Chicken Cooler", "name": "Chicken Wings", "packSize": "1 bag", "pack": 1}, 
    {"seq": 3, "location": "Chicken Cooler", "name": "Breast", "packSize": "80 per case", "pack": 80}, 
    {"seq": 4, "location": "Chicken Cooler", "name": "Legs", "packSize": "125 per case", "pack": 125}, 
    {"seq": 5, "location": "Stockroom", "name": "Shortening Fry", "packSize": "1 container", "pack": 1}, 
    {"seq": 6, "location": "Stockroom", "name": "Shortening Cube", "packSize": "1 box", "pack": 1}, 
    {"seq": 7, "location": "Stockroom", "name": "Flour Breading", "packSize": "1 bag", "pack": 1}, 
    {"seq": 9, "location": "Stockroom", "name": "Royal Mild", "packSize": "40 packs", "pack": 40}, 
    {"seq": 10, "location": "Freezer", "name": "Supremes", "packSize": "8 bags", "pack": 8}, 
    {"seq": 12, "location": "Cooler", "name": "Premade Dries", "packSize": "6 bags", "pack": 6}, 
    {"seq": 14, "location": "Cooler", "name": "Cheddar Cheese", "packSize": "6 packs", "pack": 6}, 
    {"seq": 15, "location": "Freezer", "name": "Fries", "packSize": "6 bags", "pack": 6}, 
    {"seq": 16, "location": "Freezer","name": "Bo Rounds", "packSize": "6 bags", "pack": 6}, 
    {"seq": 20, "location": "Stockroom", "name": "Pintos", "packSize": "6 cans", "pack": 6}, 
    {"seq": 21, "location": "Freezer", "name": "Mac and Cheese", "packSize": "8 bags", "pack": 8}, 
    {"seq": 23, "location": "Stockroom", "name": "Rice", "packSize": "1 bag", "pack": 1}, 
    {"seq": 27, "location": "Stockroom", "name": "Fry Seasoning", "packSize": "25 bags", "pack": 25}, 
    {"seq": 28, "location": "Stockroom", "name": "Pintos Seasoning", "packSize": "120 packs", "pack": 120}, 
    {"seq": 29, "location": "Stockroom", "name": "Dirty Rice Seasoning", "packSize": "100 packs", "pack": 100}, 
    {"seq": 30, "location": "Cooler", "name": "American Cheese", "packSize": "8 sleeves", "pack": 8}, 
    {"seq": 31, "location": "Breakfast Meats", "name": "Steak", "packSize": "6 boxes", "pack": 6}, 
    {"seq": 32, "location": "Breakfast Meats", "name": "Smoked Sausage", "packSize": "2 bags", "pack": 2}, 
    {"seq": 34, "location": "Breakfast Meats", "name": "Ham", "packSize": "3 bags", "pack": 3}, 
    {"seq": 35, "location": "Breakfast Meats", "name": "Bacon", "packSize": "4 bags", "pack": 4}, 
    {"seq": 36, "location": "Breakfast Meats", "name": "Sausage", "packSize": "2 boxes", "pack": 2}, 
    {"seq": 37, "location": "Cooler", "name": "Eggs", "packSize": "15 cartons", "pack": 15}, 
    {"seq": 38, "location": "Cooler", "name": "Whipped Margarine", "packSize": "1 tub", "pack": 1}, 
    {"seq": 42, "location": "Stockroom", "name": "Biscuit Magic", "packSize": "96 packs", "pack": 96}, 
    {"seq": 43, "location": "Cooler", "name": "Buttermilk", "packSize": "9 jugs", "pack": 9}, 
    {"seq": 48, "location": "Cooler", "name": "Orange Juice", "packSize": "24 per case", "pack": 24}, 
    {"seq": 50, "location": "Drinks", "name": "Diet Pepsi", "packSize": "1 bag in box", "pack": 1}, 
    {"seq": 51, "location": "Drinks", "name": "Diet Mountain Dew", "packSize": "1 bag in box", "pack": 1}, 
    {"seq": 55, "location": "Drinks", "name": "Mountain Dew", "packSize": "1 bag in box", "pack": 1}, 
    {"seq": 56, "location": "Drinks", "name": "Pepsi", "packSize": "1 bag in box", "pack": 1}, 
    {"seq": 60, "location": "Drinks", "name": "Tea Bags", "packSize": "110 packs", "pack": 110}, 
    {"seq": 62, "location": "Drinks", "name": "Coffee", "packSize": "176 packs", "pack": 176}, 
    {"seq": 69, "location": "Drinks", "name": "Lemonade", "packSize": "1 bag in box", "pack": 1}, 
    {"seq": 70, "location": "Drinks", "name": "Dr. Pepper", "packSize": "1 bag in box", "pack": 1}, 
    {"seq": 73, "location": "Stockroom", "name": "Sugar Granulate", "packSize": "10 bags", "pack": 10}, 
    {"seq": 90, "location": "Chicken Cooler", "name": "Bo Bites", "packSize": "8 bags", "pack": 8}, 
    {"seq": 95, "location": "Freezer", "name": "Cajun Filets", "packSize": "6 bags", "pack": 6}, 
    {"seq": 96, "location": "Freezer", "name": "Grills", "packSize": "8 bags", "pack": 8}, 
    {"seq": 97, "location": "Breakfast Meats", "name": "Bologna", "packSize": "30 bags", "pack": 30},
    {"seq": 180, "location": "Freezer", "name": "Fish", "packSize": "1 bag", "pack": 1},
    {"seq": 182, "location": "Chicken Cooler", "name": "Thigh/Leg", "packSize": "1 bag", "pack": 1}, 
    {"seq": 201, "location": "Cooler", "name": "Shredded Cheese", "packSize": "4 bags", "pack": 4}, 
    {"seq": 213, "location": "Freezer", "name": "Pork Chop", "packSize": "4 boxes", "pack": 4}, 
    {"seq": 216, "location": "Cooler", "name": "Salad Mix", "packSize": "4 bags", "pack": 4}, 
    {"seq": 219, "location": "Cooler", "name": "Shredded Lettuce", "packSize": "4 bags", "pack": 4}, 
    {"seq": 224, "location": "Cooler", "name": "Pimento Cheese", "packSize": "4 tubs", "pack": 4}, 
    {"seq": 305, "location": "Drinks", "name": "Starry", "packSize": "1 bag in box", "pack": 1}, 
    {"seq": 306, "location": "Drinks", "name": "Pepsi Zero", "packSize": "1 bag in box", "pack": 1}, 
    {"seq": 308, "location": "Drinks", "name": "Cheerwine", "packSize": "1 bag in box", "pack": 1}, 
    {"seq": 309, "location": "Drinks", "name": "Cold Brew", "packSize": "6 bottles", "pack": 6}, 
    {"seq": 310, "location": "Drinks", "name": "Sweet Cream Vanilla", "packSize": "6 cartons", "pack": 6}, 
    {"seq": 311, "location": "Drinks", "name": "Vanilla Syrup", "packSize": "12 bottles", "pack": 12}, 
    {"seq": 312, "location": "Drinks", "name": "Caramel Sauce", "packSize": "4 bottles", "pack": 4}, 
    {"seq": 314, "location": "Freezer", "name": "Bun Bird Dog", "packSize": "12 bags", "pack": 12}, 
    {"seq": 329, "location": "Stockroom", "name": "Dura Fry", "packSize": "1 bag", "pack": 1}, 
    {"seq": 330, "location": "Freezer", "name": "Buns", "packSize": "3 boxes per case / 15 bags per case", "pack": 15}, 
    {"seq": 331, "location": "Stockroom", "name": "Bo Batter", "packSize": "10 bags", "pack": 10}, 
    {"seq": 332, "location": "Stockroom", "name": "Bo Breading", "packSize": "1 bag", "pack": 1}, 
    {"seq": 334, "location": "Chicken Cooler", "name": "Bo Chicken", "packSize": "8 bags", "pack": 8}];
